[variables]
NIXPACKS_PHP_VERSION = '8.4'
NIXPACKS_NODE_VERSION = '22'
NIXPACKS_PHP_ROOT_DIR = '/app/backend/public'

[phases.install]
cmds = [
    'mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx',
    'cd backend && composer install --ignore-platform-reqs',
    'cd frontend && npm install'
]

[phases.build]
cmds = [
    'cd frontend && npm run build'
]

[start]
cmd = 'cd backend && php artisan serve --host=0.0.0.0 --port=$PORT'
